# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84b5b00bf43e72400dc330175fcadb02f1d53d8128052c7093a82604e59890e9c0ad82b9227c17affbd513dbca4dbeba863ec60929f8b5e7597f0ad677d9eaa1

test:
  secret_key_base: 22ce993a630806dd9722ad4dd1616e8fdea0de0da568c098c614bbc425180c032788f2c502838678513e7ae9036d40ed565d35c0c8836c24088c91fc4f2ba47d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
